env: "local"
#storage
http_server:
  address: "localhost"
  port: 8080
  timeout: 10s
  idle_timeout: 60s
  read_timeout: 10s
  write_timeout: 10s
#  max_header_bytes: ""

db:
  host: "192.168.99.101"
  port: "5432"
  username: "postgres"
  password: "qwerty"
  dbname: "postgres"
  sslmode: "disable"